/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence that do not exceed the nth term, find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
   if (n === 1) {
      console.log('there is no even number');
      return;
   }
   if (n === 2) {
      return 2;
   }
   let fibo = [1, 2];
   for (let i = 1; i < n - 1; i++) {
      fibo.push(fibo[i - 1] + fibo[i]);
   }
   
   let result = 0;
   for (let i = 0; i < fibo.length; i++) {
      if (fibo[i] % 2 === 0) {
         result += fibo[i];
      }
   }
   
   return result;
}

fiboEvenSum(10);